### ISSUE TITLE
建议增加刷新数据方法

### ISSUE THREAD

**Issue by doiten** [lihangleo2/ViewPager2Demo#6]
现在只有addData()和addFrontData()，缺少刷新数据的方法

**Comment by lihangleo2** [comment]
兄弟，fragment里已经有数据源了，再用户操作的时候，比如点赞，你完全是可以再fragment去更改ui的。而且更改完ui后，建议把数据源的点赞字段修改，那么在你的源数据list里也会被修改，因为内存地址是一样的。建议更新为最新版本：2.1.3。看到这里我相信你知道我表达什么了，你还有什么特殊场景吗？

**Comment by lihangleo2** [comment]
我稍后再文档里写一下刷新的方式，如果还有你的应用场景还没达到的，你可以继续重新打开这个issue

**Comment by doiten** [comment]
我想表达的是，当list很多的时候，例如有100条，我想执行刷新刷新操作notifyDataSetChanged()，将条数重置为10条

**Comment by doiten** [comment]
同理还有需求就是，可能列表里有100条数据，其中10条是违规的，这时候接收到通知就需要将它删除

**Comment by lihangleo2** [comment]
嗯，其实是缺少移除，这个api等我不忙了会加上

**Comment by lihangleo2** [comment]
刷新机制，可以去看下最近更新的文档：https://github.com/lihangleo2/ViewPager2Demo?tab=readme-ov-file#%E5%85%AD%E5%88%B7%E6%96%B0%E9%97%AE%E9%A2%98%E5%92%8C%E8%A7%86%E9%A2%91%E7%9A%84%E7%94%A8%E6%B3%95%E9%97%AE%E9%A2%98

**Comment by doiten** [comment]
万分感谢，超好用的库
