### ISSUE TITLE
同时使用addData和addFrontData会有卡顿

### ISSUE THREAD

**Issue by ppg408331701** [lihangleo2/ViewPager2Demo#8]
接口是先给小程序开发的，app开发的时候已经木已成舟

目前是获取一个item，这个item里面会有prevGuid和nextGuid，获取到这两个guid后，再在当前的item两侧生成对应的fragment，
但是如果同时使用addData和addFrontData会卡顿，不知道是不是fragment太多view的原因还是线程的问题

目前通过postDelayed把addFrontData放到150ms后执行，勉强可以

但是总觉得不对，请问我这种场景怎么处理好

**Comment by ppg408331701** [comment]
是否可以搞一个新的方法，diff，根据我传入的新的list后旧的list对比，直接diff更新

**Comment by lihangleo2** [comment]
暂时不考虑diff, addData意思很明确了，就是新添数据，并不误导人。addData()是无感刷新尾部，addFrontData()是无感刷新头部，二者都存在对adpter的刷新，但是内部存在很大的却别，这可能导致你卡顿的问题，并不是fragment多的问题，也不存在这样的问题。这2个方法用了不同的方法名去定义，也是不希望他们会被同时触发的场景
